name: Build main

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run gulp prod
        run: gulp prod

      - name: Bump tag
        id: bump-tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: patch

      - name: Change version in theme-version.php and style.css
        run: |
          sed -i "s/Version: .*/Version: ${{ steps.bump-tag.outputs.new_tag }}/g" style.css
          sed -i "s/TOPTEN_VERSION', '.*/TOPTEN_VERSION', '${{ steps.bump-tag.outputs.new_tag }}' );/g" theme-version.php

      - name: Create documentation with phpDocumentor
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -t"docs" --ignore=vendor --ignore=node_modules --ignore=fonts --ignore=includes/tfpdf

      - name: Archive documentation
        run: |
          cd docs && zip -r ../${{ github.event.repository.name }}-${{ steps.bump-tag.outputs.new_tag }}-docs.zip .

      - name: Create folder for the zip
        run: |
          mkdir "${{ github.event.repository.name }}"
          find . -maxdepth 1 \
            ! -name "${{ github.event.repository.name }}" \
            ! -name ".git" \
            ! -name ".github" \
            ! -name ".phpdoc" \
            ! -name ".editorconfig" \
            ! -name "node_modules" \
            ! -name "vendor" \
            ! -name "docs" \
            ! -name "js/src" \
            ! -name "css/src" \
            ! -name "assets/src" \
            ! -name "gulpfile.mjs" \
            ! -name "package-lock.json" \
            ! -name "package.json" \
            ! -name "composer.json" \
            ! -name "composer.lock" \
            ! -name "README.md" \
            ! -name ".eslintrc.js" \
            ! -name ".eslintignore" \
            ! -name ".gitignore" \
            ! -name ".prettierrc" \
            ! -name ".prettierignore" \
            ! -name ".stylelintrc" \
            ! -name ".stylelintignore" \
            ! -name "phpcs.xml" \
            ! -name "webpack.config.js" \
            ! -name "documentation-${{ github.event.repository.name }}.zip" \
            ! -name "topten" \
            -exec mv {} ${{ github.event.repository.name }} \;

      - name: Archive release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "${{ github.event.repository.name }}-${{ steps.bump-tag.outputs.new_tag }}.zip"
          path: "${{ github.event.repository.name }}"

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}-${{ steps.bump-tag.outputs.new_tag }}.zip,${{ github.event.repository.name }}-${{ steps.bump-tag.outputs.new_tag }}-docs"
          commit: "main"
          tag: "${{ steps.bump-tag.outputs.new_tag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          prerelease: false
